test_dir:  "/mnt/storage/siat_cjh/tmp/TrustEMG-main/self_noise_emg/emg_segments_ch6"
model_checkpoint: "/mnt/storage/siat_cjh/proj/unsup_speech_enh_adaptation/baseline/checkpoints/student/emg_remixit_v1/remixit_student_epoch_21.pt"

plot_save_dir: "./results/uda_plots"
num_plot_samples: 10
num_workers: 4

# Model hyperparameters (must match training)
out_channels: 128
in_channels: 512
num_blocks: 16
upsampling_depth: 4
enc_kernel_size: 21
enc_num_basis: 512
max_num_sources: 2

# Output transform
rescale_to_input_mixture: True
apply_mixture_consistency: False

# Data
fs: 1000
segment_length: 2000